### ISSUE TITLE
Elites not spawning whatsoever

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [arimah/PerfectedLoop#1]
Having this mod active makes it so elite enemies simply cannot spawn; here is my dependency string list:

bbepis-BepInExPack-5.4.1902
RiskofThunder-HookGenPatcher-1.2.3
tristanmcpherson-R2API-4.0.11
Lodington-Aerolt-1.2.2
EnforcerGang-MinerUnearthed-1.6.4
EnforcerGang-Enforcer-3.2.12
Paladin_Alliance-PaladinMod-1.5.6
XoXFaby-BetterUI-2.4.5
FunkFrog-and-Sipondo-ShareSuite-2.6.0
Moffein-Fix_Playercount-1.2.1
Moffein-Mercenary_Expose_Fix-1.2.1
Moffein-No_Levelup_Heal-1.0.4
VarnaScelestus-Ephemeral_Coins-1.2.2
VarnaScelestus-Enhanced_OSP-1.0.1
zombieseatflesh7-DynamicBarrierDecay-1.0.0
William758-ZetTweaks-1.1.2
Moffein-AI_Blacklist-1.4.1
Moffein-No_Void_Allies-1.0.3
Moffein-MobileTurretBuff-1.1.7
Moffein-Lunar_Wisp_Falloff-1.1.0
rainyuu-Pingprovements-1.8.0
Moffein-Acrid_Blight_Stack_Buff-1.0.1
TheTimesweeper-AcridHitboxBuff-1.1.1
Moffein-Team_Scaled_Interactables-1.0.2
arimah-MicroDropBots-1.1.0
arimah-PerfectedLoop-1.2.0
Bubbet-NotEnoughFriends-1.0.3
VTeam-Captain_Abilities_Offworld-1.0.0
RandomlyAwesome-Ye_Olde_Burn-1.0.0
Judgy-WaterTweaker-1.1.1
Faustvii-QoLChests-1.1.6
Bubbet-FixTeleportMomentum-1.0.0
ThinkInvis-Yeet-2.0.0
EnforcerGang-SniperClassic-1.0.5
SeahorseJerky-Wait_For_All_Ready_Votes-1.0.1
William758-ZetAspects-2.7.2
jiejasonliu-Reconsume-1.0.0
Mico27-FixVoidFog-1.0.0
TheTimesweeper-3rdRowCSS-1.0.0
Faustvii-LunarCoinShare-1.0.0
PseudoCoffee-RedScrapCauldron-1.0.3

**Comment by VaelophisNyx** [comment]
So yeah, this mod is definitively the one causing this issue. Removing it made elites spawn once more. Easy test is to just run Honor mode with and without it, the difference will be visible immediately

**Comment by DarkKronicle** [comment]
Same thing happening to me

**Comment by arimah** [comment]
Hello! Apologies for taking a few days to respond to this issue – I have been busy with some real-life things.

I'm terribly sorry my mod breaks your gameplay. I will have a look at it in the next few days to see if I can reproduce the issue and of course fix it.

Due to the way the mod works, there is always a risk of incompatibilities, but of course it would be ideal if it cooperates with as many mods as possible.

@ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh: thank you for posting your mod list. That gives me a lot to test with. I will let you all know if I need any further information to help resolve the issue.

**Comment by arimah** [comment]
Hello again! I have figured out what the problem is, and am in the process of fixing it. You may expect an update in the next day or so. Thank you for your patience.

**Comment by RetroRusty13** [comment]
Just tested only running this mod, I can confirm the main issue is not this mod conflicting with another. No rush on the fix, just wanted to let you know what I found in case it makes it easier to track down the bug.

**Comment by arimah** [comment]
I'm fairly confident I managed to get this fixed! Version 1.2.1 should be available in r2modman any minute now. :>

Thank you all for reporting the issue!

Have fun fighting the cute glowy Perfected Wisps.

*Edit:* If you're curious about the technical details, feel free to read the description of #2.
